// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,3,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoReq) Reset() {
	*x = PublishVideoReq{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoReq) ProtoMessage() {}

func (x *PublishVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoReq.ProtoReflect.Descriptor instead.
func (*PublishVideoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *PublishVideoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishVideoReq) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *PublishVideoReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type PublishVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=statusMsg,proto3" json:"statusMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResp) Reset() {
	*x = PublishVideoResp{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResp) ProtoMessage() {}

func (x *PublishVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResp.ProtoReflect.Descriptor instead.
func (*PublishVideoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *PublishVideoResp) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PublishVideoResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type PublishListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryId       string                 `protobuf:"bytes,2,opt,name=QueryId,proto3" json:"QueryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishListReq) Reset() {
	*x = PublishListReq{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishListReq) ProtoMessage() {}

func (x *PublishListReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishListReq.ProtoReflect.Descriptor instead.
func (*PublishListReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *PublishListReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PublishListReq) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

type PublishListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,3,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishListResp) Reset() {
	*x = PublishListResp{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishListResp) ProtoMessage() {}

func (x *PublishListResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishListResp.ProtoReflect.Descriptor instead.
func (*PublishListResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *PublishListResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *PublishListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *PublishListResp) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

type FeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	LatestTime    int64                  `protobuf:"varint,2,opt,name=LatestTime,proto3" json:"LatestTime,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedReq) Reset() {
	*x = FeedReq{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedReq) ProtoMessage() {}

func (x *FeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedReq.ProtoReflect.Descriptor instead.
func (*FeedReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *FeedReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedReq) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *FeedReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextTime      int64                  `protobuf:"varint,1,opt,name=NextTime,proto3" json:"NextTime,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,3,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,4,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedResp) Reset() {
	*x = FeedResp{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResp) ProtoMessage() {}

func (x *FeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResp.ProtoReflect.Descriptor instead.
func (*FeedResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *FeedResp) GetNextTime() int64 {
	if x != nil {
		return x.NextTime
	}
	return 0
}

func (x *FeedResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *FeedResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *FeedResp) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *User                  `protobuf:"bytes,1,opt,name=Author,proto3" json:"Author,omitempty"`
	CommentCount  int64                  `protobuf:"varint,2,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	CoverURL      string                 `protobuf:"bytes,3,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,4,opt,name=FavoriteCount,proto3" json:"FavoriteCount,omitempty"`
	ID            uint64                 `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,6,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	PlayURL       string                 `protobuf:"bytes,7,opt,name=PlayURL,proto3" json:"PlayURL,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=Title,proto3" json:"Title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *Video) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetCoverURL() string {
	if x != nil {
		return x.CoverURL
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Video) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Video) GetPlayURL() string {
	if x != nil {
		return x.PlayURL
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowCount   int64                  `protobuf:"varint,1,opt,name=FollowCount,proto3" json:"FollowCount,omitempty"`
	FollowerCount int64                  `protobuf:"varint,2,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	ID            uint64                 `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	IsFollow      bool                   `protobuf:"varint,4,opt,name=IsFollow,proto3" json:"IsFollow,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *User) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateDate    string                 `protobuf:"bytes,2,opt,name=CreateDate,proto3" json:"CreateDate,omitempty"`
	ID            uint64                 `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	User          *User                  `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

func (x *Comment) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Comment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	CommentId     string                 `protobuf:"bytes,5,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentReq) Reset() {
	*x = CommentReq{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentReq) ProtoMessage() {}

func (x *CommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentReq.ProtoReflect.Descriptor instead.
func (*CommentReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *CommentReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentReq) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *CommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type CommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	Comment       *Comment               `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResp) Reset() {
	*x = CommentResp{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResp) ProtoMessage() {}

func (x *CommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResp.ProtoReflect.Descriptor instead.
func (*CommentResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *CommentResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *CommentResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CommentResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type CommentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListReq) Reset() {
	*x = CommentListReq{}
	mi := &file_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReq) ProtoMessage() {}

func (x *CommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReq.ProtoReflect.Descriptor instead.
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{11}
}

func (x *CommentListReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CommentListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CommentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,3,rep,name=CommentList,proto3" json:"CommentList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	mi := &file_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{12}
}

func (x *CommentListResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *CommentListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CommentListResp) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

type FavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteReq) Reset() {
	*x = FavoriteReq{}
	mi := &file_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteReq) ProtoMessage() {}

func (x *FavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteReq.ProtoReflect.Descriptor instead.
func (*FavoriteReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{13}
}

func (x *FavoriteReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *FavoriteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FavoriteReq) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type FavoriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteResp) Reset() {
	*x = FavoriteResp{}
	mi := &file_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteResp) ProtoMessage() {}

func (x *FavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteResp.ProtoReflect.Descriptor instead.
func (*FavoriteResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{14}
}

func (x *FavoriteResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *FavoriteResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type FavoriteListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	QueryUserId   string                 `protobuf:"bytes,2,opt,name=QueryUserId,proto3" json:"QueryUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListReq) Reset() {
	*x = FavoriteListReq{}
	mi := &file_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListReq) ProtoMessage() {}

func (x *FavoriteListReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListReq.ProtoReflect.Descriptor instead.
func (*FavoriteListReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{15}
}

func (x *FavoriteListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FavoriteListReq) GetQueryUserId() string {
	if x != nil {
		return x.QueryUserId
	}
	return ""
}

type FavoriteListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,3,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListResp) Reset() {
	*x = FavoriteListResp{}
	mi := &file_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListResp) ProtoMessage() {}

func (x *FavoriteListResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListResp.ProtoReflect.Descriptor instead.
func (*FavoriteListResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{16}
}

func (x *FavoriteListResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *FavoriteListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *FavoriteListResp) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\"u\n" +
	"\x0fPublishVideoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aplayUrl\x18\x03 \x01(\tR\aplayUrl\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\"P\n" +
	"\x10PublishVideoResp\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x1c\n" +
	"\tstatusMsg\x18\x02 \x01(\tR\tstatusMsg\"B\n" +
	"\x0ePublishListReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x18\n" +
	"\aQueryId\x18\x02 \x01(\tR\aQueryId\"{\n" +
	"\x0fPublishListResp\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x02 \x01(\tR\tStatusMsg\x12*\n" +
	"\tVideoList\x18\x03 \x03(\v2\f.video.VideoR\tVideoList\"W\n" +
	"\aFeedReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1e\n" +
	"\n" +
	"LatestTime\x18\x02 \x01(\x03R\n" +
	"LatestTime\x12\x14\n" +
	"\x05Limit\x18\x03 \x01(\x03R\x05Limit\"\x90\x01\n" +
	"\bFeedResp\x12\x1a\n" +
	"\bNextTime\x18\x01 \x01(\x03R\bNextTime\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x02 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x03 \x01(\tR\tStatusMsg\x12*\n" +
	"\tVideoList\x18\x04 \x03(\v2\f.video.VideoR\tVideoList\"\xf2\x01\n" +
	"\x05Video\x12#\n" +
	"\x06Author\x18\x01 \x01(\v2\v.video.UserR\x06Author\x12\"\n" +
	"\fCommentCount\x18\x02 \x01(\x03R\fCommentCount\x12\x1a\n" +
	"\bCoverURL\x18\x03 \x01(\tR\bCoverURL\x12$\n" +
	"\rFavoriteCount\x18\x04 \x01(\x03R\rFavoriteCount\x12\x0e\n" +
	"\x02ID\x18\x05 \x01(\x04R\x02ID\x12\x1e\n" +
	"\n" +
	"IsFavorite\x18\x06 \x01(\bR\n" +
	"IsFavorite\x12\x18\n" +
	"\aPlayURL\x18\a \x01(\tR\aPlayURL\x12\x14\n" +
	"\x05Title\x18\b \x01(\tR\x05Title\"\x8e\x01\n" +
	"\x04User\x12 \n" +
	"\vFollowCount\x18\x01 \x01(\x03R\vFollowCount\x12$\n" +
	"\rFollowerCount\x18\x02 \x01(\x03R\rFollowerCount\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\x04R\x02ID\x12\x1a\n" +
	"\bIsFollow\x18\x04 \x01(\bR\bIsFollow\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\"t\n" +
	"\aComment\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContent\x12\x1e\n" +
	"\n" +
	"CreateDate\x18\x02 \x01(\tR\n" +
	"CreateDate\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\x04R\x02ID\x12\x1f\n" +
	"\x04User\x18\x04 \x01(\v2\v.video.UserR\x04User\"\x96\x01\n" +
	"\n" +
	"CommentReq\x12\x18\n" +
	"\aVideoId\x18\x01 \x01(\tR\aVideoId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x1e\n" +
	"\n" +
	"ActionType\x18\x03 \x01(\tR\n" +
	"ActionType\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x1c\n" +
	"\tCommentId\x18\x05 \x01(\tR\tCommentId\"u\n" +
	"\vCommentResp\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x02 \x01(\tR\tStatusMsg\x12(\n" +
	"\aComment\x18\x03 \x01(\v2\x0e.video.CommentR\aComment\"B\n" +
	"\x0eCommentListReq\x12\x18\n" +
	"\aVideoId\x18\x01 \x01(\tR\aVideoId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"\x81\x01\n" +
	"\x0fCommentListResp\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x02 \x01(\tR\tStatusMsg\x120\n" +
	"\vCommentList\x18\x03 \x03(\v2\x0e.video.CommentR\vCommentList\"_\n" +
	"\vFavoriteReq\x12\x18\n" +
	"\aVideoId\x18\x01 \x01(\tR\aVideoId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x1e\n" +
	"\n" +
	"ActionType\x18\x03 \x01(\tR\n" +
	"ActionType\"L\n" +
	"\fFavoriteResp\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x02 \x01(\tR\tStatusMsg\"K\n" +
	"\x0fFavoriteListReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12 \n" +
	"\vQueryUserId\x18\x02 \x01(\tR\vQueryUserId\"|\n" +
	"\x10FavoriteListResp\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\tR\n" +
	"StatusCode\x12\x1c\n" +
	"\tStatusMsg\x18\x02 \x01(\tR\tStatusMsg\x12*\n" +
	"\tVideoList\x18\x03 \x03(\v2\f.video.VideoR\tVideoList2\xb0\x03\n" +
	"\bVideoRpc\x12?\n" +
	"\fPublishVideo\x12\x16.video.PublishVideoReq\x1a\x17.video.PublishVideoResp\x12?\n" +
	"\x0eGetPublishList\x12\x15.video.PublishListReq\x1a\x16.video.PublishListResp\x12*\n" +
	"\aGetFeed\x12\x0e.video.FeedReq\x1a\x0f.video.FeedResp\x126\n" +
	"\rCommentAction\x12\x11.video.CommentReq\x1a\x12.video.CommentResp\x12?\n" +
	"\x0eGetCommentList\x12\x15.video.CommentListReq\x1a\x16.video.CommentListResp\x129\n" +
	"\x0eFavoriteAction\x12\x12.video.FavoriteReq\x1a\x13.video.FavoriteResp\x12B\n" +
	"\x0fGetFavoriteList\x12\x16.video.FavoriteListReq\x1a\x17.video.FavoriteListRespB\tZ\a./videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_video_proto_goTypes = []any{
	(*PublishVideoReq)(nil),  // 0: video.PublishVideoReq
	(*PublishVideoResp)(nil), // 1: video.PublishVideoResp
	(*PublishListReq)(nil),   // 2: video.PublishListReq
	(*PublishListResp)(nil),  // 3: video.PublishListResp
	(*FeedReq)(nil),          // 4: video.FeedReq
	(*FeedResp)(nil),         // 5: video.FeedResp
	(*Video)(nil),            // 6: video.Video
	(*User)(nil),             // 7: video.User
	(*Comment)(nil),          // 8: video.Comment
	(*CommentReq)(nil),       // 9: video.CommentReq
	(*CommentResp)(nil),      // 10: video.CommentResp
	(*CommentListReq)(nil),   // 11: video.CommentListReq
	(*CommentListResp)(nil),  // 12: video.CommentListResp
	(*FavoriteReq)(nil),      // 13: video.FavoriteReq
	(*FavoriteResp)(nil),     // 14: video.FavoriteResp
	(*FavoriteListReq)(nil),  // 15: video.FavoriteListReq
	(*FavoriteListResp)(nil), // 16: video.FavoriteListResp
}
var file_video_proto_depIdxs = []int32{
	6,  // 0: video.PublishListResp.VideoList:type_name -> video.Video
	6,  // 1: video.FeedResp.VideoList:type_name -> video.Video
	7,  // 2: video.Video.Author:type_name -> video.User
	7,  // 3: video.Comment.User:type_name -> video.User
	8,  // 4: video.CommentResp.Comment:type_name -> video.Comment
	8,  // 5: video.CommentListResp.CommentList:type_name -> video.Comment
	6,  // 6: video.FavoriteListResp.VideoList:type_name -> video.Video
	0,  // 7: video.VideoRpc.PublishVideo:input_type -> video.PublishVideoReq
	2,  // 8: video.VideoRpc.GetPublishList:input_type -> video.PublishListReq
	4,  // 9: video.VideoRpc.GetFeed:input_type -> video.FeedReq
	9,  // 10: video.VideoRpc.CommentAction:input_type -> video.CommentReq
	11, // 11: video.VideoRpc.GetCommentList:input_type -> video.CommentListReq
	13, // 12: video.VideoRpc.FavoriteAction:input_type -> video.FavoriteReq
	15, // 13: video.VideoRpc.GetFavoriteList:input_type -> video.FavoriteListReq
	1,  // 14: video.VideoRpc.PublishVideo:output_type -> video.PublishVideoResp
	3,  // 15: video.VideoRpc.GetPublishList:output_type -> video.PublishListResp
	5,  // 16: video.VideoRpc.GetFeed:output_type -> video.FeedResp
	10, // 17: video.VideoRpc.CommentAction:output_type -> video.CommentResp
	12, // 18: video.VideoRpc.GetCommentList:output_type -> video.CommentListResp
	14, // 19: video.VideoRpc.FavoriteAction:output_type -> video.FavoriteResp
	16, // 20: video.VideoRpc.GetFavoriteList:output_type -> video.FavoriteListResp
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
